//created:  2016-10-12 14:40:53   ./release/jssdk_cn-1.9.5.js
(function (context) {
var require,define;
(function(){function f(b){var c=b.factory;b.exports={};delete b.factory;c(function(a){var c=a;"."===a.charAt(0)&&(c=b.id.slice(0,b.id.lastIndexOf("."))+"."+a.slice(2));return require(c)},b.exports,b);return b.exports}var e={},m=[],b={};require=function(g){if(!e[g])throw"module "+g+" not found";if(g in b)throw"Cycle in require graph: "+(m.slice(b[g]).join("->")+"->"+g);if(e[g].factory)try{return b[g]=m.length,m.push(g),f(e[g])}finally{delete b[g],m.pop()}return e[g].exports};define=function(b,c){if(e[b])throw"module "+
b+" already defined";e[b]={id:b,factory:c}};define.remove=function(b){delete e[b]};define.moduleMap=e})();define("util",function(f,e,m){function b(a){var c,p=a,l;if(a&&((l=a instanceof Array)||a instanceof Object))for(c in p=l?[]:{},a)a.hasOwnProperty(c)&&(p[c]=b(a[c]));return p}var g=f("constant"),c=Object.prototype.toString,a={getTop:function(b){var c=b.offsetTop;null!=b.offsetParent&&(c+=a.getTop(b.offsetParent));return c},getLeft:function(b){var c=b.offsetLeft;null!=b.offsetParent&&(c+=a.getLeft(b.offsetParent));return c},getCss3offsetTop:function(b){var c=getComputedStyle(b,null).webkitTransform,
c="none"==c?0:parseInt(c.split(",")[5].replace(")",""));"BODY"!=b.parentNode.tagName&&(c+=a.getCss3offsetTop(b.parentNode));return c},getCss3offsetLeft:function(b){var c=getComputedStyle(b,null).webkitTransform,c="none"==c?0:parseInt(c.split(",")[4]);"BODY"!=b.parentNode.tagName&&(c+=a.getCss3offsetLeft(b.parentNode));return c},getNodePosById:function(b){return(b=document.getElementById(b))?[a.getLeft(b)+a.getCss3offsetLeft(b),a.getTop(b)+a.getCss3offsetTop(b),b.offsetWidth,b.offsetHeight]:""}};e.getPlatform=
function(){return window.UCShellJava?g.platform.ANDROID:window.__BrowserJSBridgeObj?g.platform.IPHONE:g.platform.OTHERS};e.isString=function(a){return"[object String]"===c.call(a)};e.isFunction=function(a){return"[object Function]"===c.call(a)};e.isArray=function(a){return"[object Array]"===c.call(a)};e.isEmptyObj=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};e.clone=b;e.getNodePosById=a.getNodePosById;e.debugLog=function(a){if(ucapi&&ucapi.debug){console.log(a);var b=navigator.userAgent;
(b.match(/(Android)\s+([\d.]+)/)||b.match(/(iPhone\sOS)\s([\d_]+)/))&&alert(a)}};e.log=function(a,b){encodeURIComponent(location.href)}});define("constant",function(f,e,m){e.platform={ALL:"all",ANDROID:"android",IPHONE:"iphone",OTHERS:"others"};e.debug=!1;e.callbackStatus={OK:0,ACCESS_DENY:1,INVALID_METHOD:2,INVALID_PARAM:3,UNKNOWN_ERROR:4};e.callbackStatusMessage=["OK","ACCESS_DENY","INVALID_METHOD","INVALID_PARAMS","UNKNOWN_ERROR"]});define("bridge",function(f,e,m){function b(a){a=a.replace("+","%20");return decodeURIComponent(a)}function g(a){if(ucapi.invoke)return!0;a&&a.fail&&a.fail.call(this,{errCode:k.callbackStatus.INVALID_METHOD,errMsg:"ucapi.invoke not exsit, should load in UCBrowser !"})}function c(a,b,c){a&&a.call(this,{errCode:b,errMsg:c})}var a=f("util"),k=f("constant"),n={};e.exec=function(b,l,d){a.log(b,"invoke");if(g(l)){var e=a.getPlatform();if(d!==k.platform.ALL&&e!==d)l&&l.fail&&c(l.fail,k.callbackStatus.INVALID_METHOD,
"this api not supported this platform");else{if(l&&l.fail){var f=l.fail;l.fail=function(c){a.log(b,"fail");c.errMsg=k.callbackStatusMessage[c.errCode];f.call(this,c)}}ucapi.invoke(b,l)}}};e.subscribeEvent=function(a,b,c){if(g(b)&&a&&b.success)ucapi.on(a,b.success)};e.onEvent=function(b,c,d){a.log(b,"invoke");c&&(a.getPlatform()!=k.platform.ANDROID||"biz.onShare"!=b||!c.screenshotHtmlNodeId||""==c.screenshotHtmlNodeId||c.screenshotRect&&""!=c.screenshotRect||(d=a.getNodePosById(c.screenshotHtmlNodeId),
""!=d&&(d=d.join(",")),c.screenshotRect=d),n[b]=c)};e.triggerEvent=function(b){if(b&&b.method)if(n[b.method]){var c=n[b.method];if(a.getPlatform()==k.platform.ANDROID){if(b.channel&&"invokeJs"==b.channel){var d="";c.trigger&&(d=c.trigger(b.data));void 0==d?(b=a.clone(c),b.success&&delete b.success,b.fail&&delete b.fail,b.trigger&&delete b.trigger):b=d}else d={},d.method=b.method,b.callbackId&&(d.callbackId=b.callbackId),d.args=c,ucapi.base.triggerEventCallback(d),b=void 0;return b}((d=c.trigger&&
c.trigger(b.data))&&"object"==typeof d||b.callbackId)&&ucapi.base.triggerEventCallback({method:b.method,callbackId:b.callbackId,args:c,trigger_result:d})}else a.getPlatform()!==k.platform.ANDROID&&b.callbackId&&b.method&&"biz.onShare"!=b.method&&ucapi.base.triggerEventCallback({method:b.method,callbackId:b.callbackId})};e.invokeJs=function(c){if(c.js&&c.callbackId){var e=b(c.js);c={result:"",callbackId:c.callbackId};eval(e);if(void 0!=ucapi.base.injectInvokeJs)try{a.log("base.injectInvokeJs","inject");
var d=ucapi.base.injectInvokeJs();d||(d="");c.result=d}catch(g){a.log("base.injectInvokeJs","error")}ucapi.base.invokeJsCallback(c)}}});define("apidef",function(f,e,m){var b=f("constant").platform,g=f("apiCompatibleImpl"),c=f("bridge");e.ucapi={base:{checkAPI:function(a){c.exec("base.checkAPI",a,b.ALL)},getVersion:function(a){c.exec("base.getVersion",a,b.ALL)},displayMode:function(a){c.exec("base.displayMode",a,b.ALL)},imageMode:function(a){c.exec("base.imageMode",a,b.ALL)},onDisplayModeChange:function(a){c.subscribeEvent("base.onDisplayModeChange",a,b.ANDROID)},onImageModeChange:function(a){c.subscribeEvent("base.onImageModeChange",
a,b.ANDROID)},triggerEvent:function(a){return c.triggerEvent(a)},triggerEventCallback:function(a){c.exec("base.triggerEventCallback",a,b.ALL)},invokeJs:function(a){c.invokeJs(a)},invokeJsCallback:function(a){c.exec("base.invokeJsCallback",a,b.ANDROID)},setImageReader:function(a){c.exec("base.setImageReader",a,b.IPHONE)},sendBeacon:function(a){c.exec("base.sendBeacon",a,b.IPHONE)},copyToClipboard:function(a){c.exec("base.copyToClipboard",a,b.ALL)}},device:{batteryLevel:function(a){c.exec("device.batteryLevel",
a,b.ALL)}},biz:{queryApp:function(a){c.exec("biz.queryApp",a,b.ALL)},startApp:function(a){c.exec("biz.startApp",a,b.ALL)},quickDownload:function(a){c.exec("biz.quickDownload",a,b.ANDROID)},queryAppIsDl:function(a){c.exec("biz.queryAppIsDl",a,b.ANDROID)},installApp:function(a){c.exec("biz.installApp",a,b.ANDROID)},checkUpdate:function(a){c.exec("biz.checkUpdate",a,b.ANDROID)},copyPlainTextToClipboard:function(a){c.exec("biz.copyPlainTextToClipboard",a,b.IPHONE)},saveImageToPhotoAlbum:function(a){c.exec("biz.saveImageToPhotoAlbum",
a,b.IPHONE)},openWindow:function(a){c.exec("biz.openWindow",a,b.ANDROID)},customBar:function(a){c.exec("biz.customBar",a,b.ALL)},setStatusBarBgColor:function(a){c.exec("biz.setStatusBarBgColor",a,b.ALL)},share:function(a){g.exec("biz.share",a,b.ALL)},onShare:function(a){c.onEvent("biz.onShare",a,b.ALL)},loadBizModeUrl:function(a){c.exec("biz.loadBizModeUrl",a,b.IPHONE)},customSiteNotify:function(a){c.exec("biz.customSiteNotify",a,b.ANDROID)},openVoice:function(a){c.exec("biz.openVoice",a,b.ALL)},
createDestopShortcut:function(a){c.exec("biz.createDestopShortcut",a,b.ANDROID)},openInExternal:function(a){c.exec("biz.openInExternal",a,b.IPHONE)},openAppStore:function(a){c.exec("biz.openAppStore",a,b.IPHONE)},installIPA:function(a){c.exec("biz.installIPA",a,b.IPHONE)},setFullScreen:function(a){c.exec("biz.setFullScreen",a,b.ALL)},gous:function(a){c.exec("biz.gous",a,b.IPHONE)},onBizItemClicked:function(a){c.onEvent("biz.onBizItemClicked",a,b.ALL)},imageDidFlip:function(a){c.exec("biz.imageDidFlip",
a,b.ALL)},hiddenComponent:function(a){c.exec("biz.hiddenComponent",a,b.ALL)},closeWebPage:function(a){c.exec("biz.closeWebPage",a,b.ALL)},handlePageError:function(a){c.exec("biz.handlePageError",a,b.ANDROID)},getUserType:function(a){c.exec("biz.getUserType",a,b.ALL)},getNewbieType:function(a){c.exec("biz.getNewbieType",a,b.ALL)},ucparams:function(a){c.exec("biz.ucparams",a,b.ANDROID)},openPicViewer:function(a){c.exec("biz.openPicViewer",a,b.ANDROID)},handleExt:function(a){c.exec("biz.handleExt",a,
b.ANDROID)}},video:{getFollowedVideos:function(a){c.exec("video.getFollowedVideos",a,b.ALL)},play:function(a){c.exec("video.play",a,b.ALL)},onPlayEnd:function(a){c.onEvent("video.onPlayEnd",a,b.ALL)},getPlayList:function(a){c.exec("video.getPlayList",a,b.ALL)}},theme:{setEnableSwipeGesture:function(a){c.exec("theme.setEnableSwipeGesture",a,b.ANDROID)},applySkin:function(a){c.exec("theme.applySkin",a,b.ANDROID)},onlineSkinPreview:function(a){c.exec("theme.onlineSkinPreview",a,b.ANDROID)},getThemeList:function(a){c.exec("theme.getThemeList",
a,b.ANDROID)}},infoflow:{notifyFlushWebItemInfo:function(a){c.exec("infoflow.notifyFlushWebItemInfo",a,b.ALL)},openInfoFlowImageGallery:function(a){c.exec("infoflow.openInfoFlowImageGallery",a,b.ALL)},notifyContentPosState:function(a){c.exec("infoflow.notifyContentPosState",a,b.ALL)},getNewsData:function(a){c.exec("infoflow.getNewsData",a,b.ALL)},priseFinishNotify:function(a){c.exec("infoflow.priseFinishNotify",a,b.ALL)},queryPageInfo:function(a){c.exec("infoflow.queryPageInfo",a,b.IPHONE)},backToList:function(a){c.exec("infoflow.backToList",
a,b.ANDROID)},openChannelWindow:function(a){c.exec("infoflow.openChannelWindow",a,b.ALL)},onUserClick:function(a){c.exec("infoflow.onUserClick",a,b.IPHONE)},statsUserClick:function(a){c.exec("infoflow.statsUserClick",a,b.ANDROID)},userDidScroll:function(a){c.exec("infoflow.userDidScroll",a,b.ALL)},notifyFollowInfo:function(a){c.exec("infoflow.notifyFollowInfo",a,b.ALL)},flushWeMediaInfo:function(a){c.exec("infoflow.flushWeMediaInfo",a,b.ALL)},switchSearch:function(a){c.exec("infoflow.switchSearch",
a,b.ALL)},statEvent:function(a){c.exec("infoflow.statEvent",a,b.ALL)},interceptUrl:function(a){c.exec("infoflow.interceptUrl",a,b.ANDROID)},setArticleRect:function(a){c.exec("infoflow.setArticleRect",a,b.ANDROID)},jumpPage:function(a){c.exec("infoflow.jumpPage",a,b.IPHONE)},openArticleItemWithInfo:function(a){c.exec("infoflow.openArticleItemWithInfo",a,b.ALL)}},promotion:{getContent:function(a){c.exec("promotion.getContent",a,b.IPHONE)},actionNotify:function(a){c.exec("promotion.actionNotify",a,b.IPHONE)},
getHcAd:function(a){c.exec("promotion.getHcAd",a,b.ANDROID)}},comment:{configInput:function(a){c.exec("comment.configInput",a,b.ALL)},onSendComment:function(a){},onSendComment3rd:function(a){},notifySendResult:function(a){c.exec("comment.notifySendResult",a,b.ALL)},openCommentWebview:function(a){c.exec("comment.openCommentWebview",a,b.IPHONE)},notifyCommentCount:function(a){c.exec("comment.notifyCommentCount",a,b.ALL)},setSendCommentPlaceHolder:function(a){c.exec("comment.setSendCommentPlaceHolder",
a,b.ALL)}},account:{openLoginWindow:function(a){c.exec("account.openLoginWindow",a,b.ALL)},getUserInfo:function(a){c.exec("account.getUserInfo",a,b.ALL)},onAccountStateChange:function(a){c.onEvent("account.onAccountStateChange",a,b.ALL)}},ucmap:{launchUCMap:function(a){c.exec("ucmap.launchUCMap",a,b.ALL)},config:function(a){c.exec("ucmap.config",a,b.ALL)}},novel:{getUserInfo:function(a){c.exec("novel.getUserInfo",a,b.ALL)},openRechargePanel:function(a){c.exec("novel.openRechargePanel",a,b.ANDROID)},
openBatchBuyPanel:function(a){c.exec("novel.openBatchBuyPanel",a,b.ANDROID)},updateProgressData:function(a){c.exec("novel.updateProgressData",a,b.ALL)},addToBookshelf:function(a){c.exec("novel.addToBookshelf",a,b.ALL)},getBookStatus:function(a){c.exec("novel.getBookStatus",a,b.ALL)},getReadingConfig:function(a){c.exec("novel.getReadingConfig",a,b.ALL)},setReadingConfig:function(a){c.exec("novel.setReadingConfig",a,b.ALL)},stat:function(a){c.exec("novel.stat",a,b.ALL)}},feedback:{getScreenshot:function(a){c.exec("feedback.getScreenshot",
a,b.ANDROID)}},mall:{missionDetail:function(a){c.exec("mall.missionDetail",a,b.IPHONE)},doMission:function(a){c.exec("mall.doMission",a,b.IPHONE)}},pay:{doPay:function(a){c.exec("pay.doPay",a,b.ALL)},openOrderCenter:function(a){c.exec("pay.openOrderCenter",a,b.ALL)},onPaymentStateChange:function(a){c.onEvent("pay.onPaymentStateChange",a,b.ALL)}},cms:{executeAction:function(a){c.exec("cms.executeAction",a,b.ALL)}},settings:{switchInputMethod:function(a){c.exec("settings.switchInputMethod",a,b.ANDROID)}},
smspring:{interactiveEvent:function(a){c.exec("smspring.interactiveEvent",a,b.IPHONE)}},wemedia:{openHomePage:function(a){c.exec("wemedia.openHomePage",a,b.ALL)},onFollow:function(a){c.onEvent("wemedia.onFollow",a,b.ALL)},followWemedia:function(a){c.exec("wemedia.followWemedia",a,b.ALL)},switchToGuide:function(a){c.exec("wemedia.switchToGuide",a,b.ALL)},releaseStrategy:function(a){c.exec("wemedia.releaseStrategy",a,b.ALL)},playVideo:function(a){c.exec("wemedia.playVideo",a,b.ALL)},playVideoList:function(a){c.exec("wemedia.playVideoList",
a,b.ALL)},onPlayNextVideo:function(a){c.onEvent("wemedia.onPlayNextVideo",a,b.ALL)},onPlayingVideoItem:function(a){c.onEvent("wemedia.onPlayingVideoItem",a,b.ALL)}},smlbs:{locationEvent:function(a){c.exec("smlbs.locationEvent",a,b.IPHONE)}},pp:{setNoBlock:function(a){c.exec("pp.setNoBlock",a,b.ANDROID)}},notification:{getMsgBoxInfo:function(a){c.exec("notification.getMsgBoxInfo",a,b.ANDROID)}},spam:{getActivityToken:function(a){c.exec("spam.getActivityToken",a,b.ALL)},encrypt:function(a){c.exec("spam.encrypt",
a,b.ALL)},sign:function(a){c.exec("spam.sign",a,b.ALL)}},activity:{playGameNotify:function(a){c.exec("activity.playGameNotify",a,b.ALL)},onPlayGameCallback:function(a){c.onEvent("activity.onPlayGameCallback",a,b.ALL)}}}});define("apiCompatibleImpl",function(f,e,m){function b(a,b){for(var c="",e=a.split(","),g=0;g<e.length;g++){var f=e[g],k=b[e[g]];k&&(f=k);c=""!==c?c+","+f:f}return c}function g(a,b,c){a&&a.call(this,{errCode:b,errMsg:c})}var c=f("constant"),a=f("util"),k=f("bridge"),n={QRcode:"QRcodeGenerator"},p={SinaWeibo:"kSinaWeibo",WechatFriends:"kWeixin",WechatTimeline:"kWeixinFriend",QQ:"kQQ",Qzone:"KQZone",QRcodeGenerator:"QRcodeGenerator",DingDing:"DingDing",ClipBoard:"ClipBoard"};e.exec=function(e,d,f){a.log(e,
"apiCompatibleImpl exec");var h;ucapi.invoke?h=!0:(g(d.fail,c.callbackStatus.INVALID_METHOD,"ucapi.invoke not exsit, should load in UCBrowser !"),h=!1);h?(h=a.getPlatform(),f!==c.platform.ALL&&h!==f?d&&d.fail&&g(d.fail,c.callbackStatus.INVALID_METHOD,"this api not supported this platform"):("biz.share"===e?(a.getPlatform()==c.platform.ANDROID?(d.sourceUrl&&(d.url=d.sourceUrl,delete d.sourceUrl),d.imageUrl&&(d.image_url=d.imageUrl,delete d.imageUrl),d.screenshotHtmlNodeId&&(""!=d.screenshotHtmlNodeId&&
(h=a.getNodePosById(d.screenshotHtmlNodeId),""!=h&&(h=h.join(",")),d.share_rect=h),delete d.screenshotHtmlNodeId),d.target&&(d.target=b(d.target,n)),d.disableTarget&&(d.invisible_platforms=b(d.disableTarget,n),delete d.disableTarget),window.ucweb.startRequest("shell.share",[JSON.stringify(d)])):(d.screenshotHtmlNodeId&&(d.htmlNode=d.screenshotHtmlNodeId,delete d.screenshotHtmlNodeId),d.target&&(d.target=b(d.target,p)),d.disableTarget&&(d.disableTarget=b(d.disableTarget,p)),d.type&&(d.shareStyle=d.type,
delete d.type),d.triggerFn&&(d.jsCallBackFun=d.triggerFn,delete d.triggerFn),ucbrowser.web_shareEX(JSON.stringify(d))),h=!0):h=!1,h||k.exec(e,d,f))):a.log(e,"should load in UCBrowser")}});var apiDef=require("apidef"),util=require("util");window.ucapi&&window.ucapi.debug&&(window.onerror=function(f){util.debugLog("onerror:"+f)});window.ucapi?extenducapi():window.ucapi=apiDef.ucapi;function extenducapi(){var f=apiDef.ucapi,e;for(e in f)window.ucapi[e]=f[e]};
}(window));
